version: "2"

checks:
  argument-count:
    config:
      threshold: 7
  file-lines:
    config:
      threshold: 900
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 30
  method-lines:
    config:
      threshold: 30
  similar-code:
    config:
      threshold: 40
      exclude_patterns:
      - "tests/"

plugins:
  duplication:
    enabled: true
    config:
      count_threshold: 3
      languages:
        python:
            python_version: 3
  sonar-python:
    enabled: true
    config:
      tests_patterns:
      tests/

exclude_patterns:
- "docs/"
- "!docs/conf.py"
- "*.rst"
- "*.txt"
- "scripts/dataextend.py"
